"use strict";

const fs = require("node:fs");
const path = require("node:path");
const os = require("node:os");
const { spawn } = require("node:child_process");

const APP_NAME = "Clearmind";

function startupFolderWin() {
  const appdata = process.env.APPDATA || path.join(os.homedir(), "AppData", "Roaming");
  return path.join(appdata, "Microsoft", "Windows", "Start Menu", "Programs", "Startup");
}

function vbsPath() {
  return path.join(startupFolderWin(), `${APP_NAME}.vbs`);
}

function plistPath() {
  return path.join(os.homedir(), "Library", "LaunchAgents", `app.${APP_NAME.toLowerCase()}.plist`);
}

function desktopPath() {
  const xdg = process.env.XDG_CONFIG_HOME || path.join(os.homedir(), ".config");
  return path.join(xdg, "autostart", `${APP_NAME.toLowerCase()}.desktop`);
}

/**
 * Build a VBS that runs `node cli.js --tray --skip-update` in a hidden window
 * so Windows users don't see a black cmd flash on every boot.
 */
function vbsContent(nodeExe, cliJs) {
  const esc = (s) => s.replace(/"/g, '""');
  return [
    `' Auto-generated by Clearmind. Edit at your own risk.`,
    `Set WshShell = CreateObject("WScript.Shell")`,
    `WshShell.Run """${esc(nodeExe)}"" ""${esc(cliJs)}"" --tray --skip-update", 0, False`,
    ``,
  ].join("\r\n");
}

function enable(nodeExe, cliJs) {
  if (process.platform === "win32") {
    const dir = startupFolderWin();
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(vbsPath(), vbsContent(nodeExe, cliJs), "utf8");
    return { ok: true, path: vbsPath() };
  }
  if (process.platform === "darwin") {
    const file = plistPath();
    fs.mkdirSync(path.dirname(file), { recursive: true });
    const plist = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyLists-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key><string>app.${APP_NAME.toLowerCase()}</string>
  <key>ProgramArguments</key>
  <array>
    <string>${nodeExe}</string>
    <string>${cliJs}</string>
    <string>--tray</string>
    <string>--skip-update</string>
  </array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><false/>
</dict>
</plist>
`;
    fs.writeFileSync(file, plist, "utf8");
    try { spawn("launchctl", ["load", file], { stdio: "ignore" }); } catch (_) { /* best-effort */ }
    return { ok: true, path: file };
  }
  // Linux
  const file = desktopPath();
  fs.mkdirSync(path.dirname(file), { recursive: true });
  const desktop = `[Desktop Entry]
Type=Application
Name=${APP_NAME}
Exec="${nodeExe}" "${cliJs}" --tray --skip-update
X-GNOME-Autostart-enabled=true
Comment=Bộ não phụ — chạy ngầm cùng máy
`;
  fs.writeFileSync(file, desktop, "utf8");
  return { ok: true, path: file };
}

function disable() {
  let file;
  if (process.platform === "win32") file = vbsPath();
  else if (process.platform === "darwin") file = plistPath();
  else file = desktopPath();
  if (fs.existsSync(file)) {
    try {
      if (process.platform === "darwin") spawn("launchctl", ["unload", file], { stdio: "ignore" });
    } catch (_) { /* swallow */ }
    fs.unlinkSync(file);
    return { ok: true };
  }
  return { ok: true, alreadyDisabled: true };
}

function isEnabled() {
  if (process.platform === "win32") return fs.existsSync(vbsPath());
  if (process.platform === "darwin") return fs.existsSync(plistPath());
  return fs.existsSync(desktopPath());
}

module.exports = { enable, disable, isEnabled, vbsPath, plistPath, desktopPath };
