"use strict";

const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { execFileSync } = require("node:child_process");

/**
 * Two related Windows-registry registrations for Clearmind:
 *
 *   1) `clearmind://` URL scheme — so toast action buttons can invoke our
 *      local handler without bouncing through the browser.
 *   2) AppUserModelID `Clearmind` — required for Windows ToastGeneric to
 *      actually render the appLogoOverride icon + action buttons. Without
 *      this, ToastNotificationManager::CreateToastNotifier('Clearmind')
 *      fails silently and falls back to a generic notifier ('Microsoft.
 *      Windows.Explorer') which uses Explorer's icon and strips features.
 *
 * Both write to HKCU only — no admin needed.
 */

const SCHEME = "clearmind";
const AUM_ID = "Clearmind";

/**
 * Build the contents of the VBS launcher that wraps the node URL handler
 * with a hidden console. Windows protocol-handler activations are
 * launched via ShellExecute, which honours the registered command line
 * verbatim — so registering `node.exe url-handler.js "%1"` directly
 * caused a black console window to flash for ~100ms whenever the user
 * clicked a toast action button (node.exe is a CONSOLE subsystem binary
 * on Windows and gets a console attached on creation unless the parent
 * passes a hidden window style).
 *
 * Solution: register `wscript.exe launcher.vbs "%1"` instead. wscript
 * is a Windows-subsystem host (no console), and the VBS uses
 * `WshShell.Run(cmd, 0, false)` where the second arg `0` is `vbHide` —
 * the spawned node process gets no visible console window.
 *
 * Same trick autostart.js already uses for the boot-time tray launch.
 */
function vbsLauncherContent(nodeExe, handlerJs) {
  // VBS string literals escape double-quotes by doubling them ("").
  const escVbs = (s) => s.replace(/"/g, '""');
  return [
    `' Auto-generated by Clearmind url-scheme.js. Hidden launcher for clearmind://`,
    `' Receives the activation URL as WScript.Arguments(0) and forwards to node`,
    `' with vbHide so no console flashes when toast action buttons fire.`,
    `Set sh = CreateObject("WScript.Shell")`,
    `args = ""`,
    `For i = 0 To WScript.Arguments.Count - 1`,
    `  args = args & " """ & WScript.Arguments(i) & """"`,
    `Next`,
    `sh.Run """${escVbs(nodeExe)}"" ""${escVbs(handlerJs)}""" & args, 0, False`,
    ``,
  ].join("\r\n");
}

function vbsLauncherPath() {
  return path.resolve(__dirname, "url-handler-launcher.vbs");
}

function registerUrlScheme({ nodeExe, handlerJs } = {}) {
  if (process.platform !== "win32") return { ok: false, reason: "non-win32" };

  const node = nodeExe || process.execPath;
  const handler = handlerJs || path.resolve(__dirname, "url-handler.js");
  const launcher = vbsLauncherPath();

  // Write/refresh the VBS launcher every register pass. Paths get baked
  // in here so the launcher is tied to this specific install — moving
  // the cli/ directory and rerunning the CLI will rewrite both the VBS
  // and the registry value pointing at it.
  try {
    fs.writeFileSync(launcher, vbsLauncherContent(node, handler), "utf8");
  } catch (e) {
    return { ok: false, reason: `vbs write failed: ${(e && e.message) || e}` };
  }

  // wscript.exe lives in %SYSTEMROOT%\System32 on every Windows install.
  // Falling back to the bare name lets PATH resolve it.
  const wscript =
    (process.env.SYSTEMROOT
      ? path.join(process.env.SYSTEMROOT, "System32", "wscript.exe")
      : "wscript.exe");

  // Use a .reg file rather than `reg.exe add` so we can safely embed paths
  // that contain spaces, backslashes, and quotes without per-arg quoting
  // gymnastics. regedit /s consumes it silently.
  const tmpReg = path.join(os.tmpdir(), `clearmind-url-scheme-${Date.now()}.reg`);
  const cmdLine =
    `\\"${wscript.replace(/\\/g, "\\\\")}\\" \\"${launcher.replace(/\\/g, "\\\\")}\\" \\"%1\\"`;
  const content = [
    "Windows Registry Editor Version 5.00",
    "",
    `[HKEY_CURRENT_USER\\Software\\Classes\\${SCHEME}]`,
    `@="URL:Clearmind Protocol"`,
    `"URL Protocol"=""`,
    "",
    `[HKEY_CURRENT_USER\\Software\\Classes\\${SCHEME}\\DefaultIcon]`,
    `@="\\"${node.replace(/\\/g, "\\\\")}\\",1"`,
    "",
    `[HKEY_CURRENT_USER\\Software\\Classes\\${SCHEME}\\shell]`,
    "",
    `[HKEY_CURRENT_USER\\Software\\Classes\\${SCHEME}\\shell\\open]`,
    "",
    `[HKEY_CURRENT_USER\\Software\\Classes\\${SCHEME}\\shell\\open\\command]`,
    `@="${cmdLine}"`,
    "",
  ].join("\r\n");

  try {
    // UTF-16 LE w/ BOM is the canonical .reg encoding. ASCII works for our
    // content but we play safe — the cmdLine includes backslashes only.
    const buf = Buffer.concat([Buffer.from([0xff, 0xfe]), Buffer.from(content, "utf16le")]);
    fs.writeFileSync(tmpReg, buf);
    execFileSync("reg.exe", [
      "import", tmpReg,
    ], { windowsHide: true, stdio: "ignore" });
    return { ok: true };
  } catch (e) {
    return { ok: false, reason: (e && e.message) || String(e) };
  } finally {
    try { fs.unlinkSync(tmpReg); } catch (_) {}
  }
}

/** Verify the scheme is currently registered to our wscript+VBS launcher.
 *  Old registrations (direct node.exe → url-handler.js) miss this check on
 *  purpose so the next CLI start re-registers via the silent VBS path. */
function isRegistered() {
  if (process.platform !== "win32") return false;
  try {
    const out = execFileSync(
      "reg.exe",
      ["query", `HKCU\\Software\\Classes\\${SCHEME}\\shell\\open\\command`],
      { windowsHide: true, encoding: "utf8" }
    );
    return /url-handler-launcher\.vbs/i.test(out);
  } catch (_) {
    return false;
  }
}

/**
 * Register the Clearmind AppUserModelID with Windows so ToastNotificationManager
 * can find it. Writes:
 *   HKCU\Software\Classes\AppUserModelId\Clearmind
 *     DisplayName      = "Clearmind"
 *     IconUri          = absolute path to icon-256.png
 *     IconBackgroundColor = "#6366F1" (indigo brand)
 *
 * Without this entry, the ToastGeneric template's appLogoOverride image
 * never appears and action buttons may also be stripped — Windows decides
 * the notifier is "anonymous" and downgrades the toast template.
 */
function registerAumId({ iconPath } = {}) {
  if (process.platform !== "win32") return { ok: false, reason: "non-win32" };

  const icon = iconPath || path.resolve(__dirname, "assets", "icon-256.png");
  if (!fs.existsSync(icon)) {
    return { ok: false, reason: `Icon not found: ${icon}` };
  }
  // Backslashes in registry .reg-file values must be doubled.
  const iconEscaped = icon.replace(/\\/g, "\\\\");

  const tmpReg = path.join(os.tmpdir(), `clearmind-aum-${Date.now()}.reg`);
  const content = [
    "Windows Registry Editor Version 5.00",
    "",
    `[HKEY_CURRENT_USER\\Software\\Classes\\AppUserModelId\\${AUM_ID}]`,
    `"DisplayName"="${AUM_ID}"`,
    `"IconUri"="${iconEscaped}"`,
    `"IconBackgroundColor"="#6366F1"`,
    "",
  ].join("\r\n");

  try {
    const buf = Buffer.concat([
      Buffer.from([0xff, 0xfe]),
      Buffer.from(content, "utf16le"),
    ]);
    fs.writeFileSync(tmpReg, buf);
    execFileSync("reg.exe", ["import", tmpReg], {
      windowsHide: true,
      stdio: "ignore",
    });
    return { ok: true };
  } catch (e) {
    return { ok: false, reason: (e && e.message) || String(e) };
  } finally {
    try { fs.unlinkSync(tmpReg); } catch (_) {}
  }
}

function isAumIdRegistered() {
  if (process.platform !== "win32") return false;
  try {
    const out = execFileSync(
      "reg.exe",
      ["query", `HKCU\\Software\\Classes\\AppUserModelId\\${AUM_ID}`, "/v", "IconUri"],
      { windowsHide: true, encoding: "utf8" }
    );
    return /icon-256\.png/i.test(out);
  } catch (_) {
    return false;
  }
}

module.exports = {
  registerUrlScheme,
  isRegistered,
  registerAumId,
  isAumIdRegistered,
  SCHEME,
  AUM_ID,
};
